apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: small-size
  namespace: namespace-configuration-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  selector:
    matchLabels:
      size: small  
  resources:
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: small-size  
    spec:
      hard:
        pods: "10"
        requests.cpu: "1"
        requests.memory: 5Gi
  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: default-limit-range
    spec:
      limits:
      - defaultRequest:
          cpu: 50m
          memory: 64Mi
        type: Container
