apiVersion: v1
kind: Namespace
metadata:
  name: namespace-configuration-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: namespace-configuration-operator
  namespace: namespace-configuration-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: alpha
  name: namespace-configuration-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: small-size
  namespace: namespace-configuration-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  selector:
    matchLabels:
      size: small  
  resources:
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: small-size  
    spec:
      hard:
        pods: "10"
        requests.cpu: "1"
        requests.memory: 5Gi
